/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

/**
 *
 * @author yangel
 */
public class Cargar_Gr extends javax.swing.JFrame {

    /**
     * Creates new form Cargar_Gr
     */
    public Cargar_Gr() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        Carga1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Ciudad_l1 = new javax.swing.JTextField();
        Hormigas1 = new javax.swing.JTextField();
        Ciudades1 = new javax.swing.JTextField();
        Ciclos1 = new javax.swing.JTextField();
        Feromonas1 = new javax.swing.JTextField();
        Visibilidad1 = new javax.swing.JTextField();
        Evaporacion1 = new javax.swing.JTextField();
        Ciudad_p1 = new javax.swing.JTextField();
        Carga2 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        Ciudad_l2 = new javax.swing.JTextField();
        Hormigas2 = new javax.swing.JTextField();
        Ciudades2 = new javax.swing.JTextField();
        Ciclos2 = new javax.swing.JTextField();
        Feromonas2 = new javax.swing.JTextField();
        Visibilidad2 = new javax.swing.JTextField();
        Evaporacion2 = new javax.swing.JTextField();
        Ciudad_p2 = new javax.swing.JTextField();
        Carga3 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        Ciudad_l3 = new javax.swing.JTextField();
        Hormigas3 = new javax.swing.JTextField();
        Ciudades3 = new javax.swing.JTextField();
        Ciclos3 = new javax.swing.JTextField();
        Feromonas3 = new javax.swing.JTextField();
        Visibilidad3 = new javax.swing.JTextField();
        Evaporacion3 = new javax.swing.JTextField();
        Ciudad_p3 = new javax.swing.JTextField();
        Salida = new javax.swing.JButton();
        Volver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setText("Cargar Grafo");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 1100, 20));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Tercer grafo guardado");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Primer grafo guardado");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Segundo grafo guardado");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 1100, 20));

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 1100, 20));

        Carga1.setText("Cargar");
        Carga1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Carga1ActionPerformed(evt);
            }
        });
        getContentPane().add(Carga1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 270, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel5.setText("- Número de hormigas:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel6.setText("- Número de ciudades:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel7.setText("- Número de ciclos:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel8.setText("- Grado de feromonas:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel9.setText("- Grado de visibilidad:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel10.setText("- Factor de evaporación: ");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel11.setText("- Ciudad de partida:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 210, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel12.setText("- Ciudad de llegada:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 240, -1, -1));

        Ciudad_l1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Ciudad_l1.setText("0");
        getContentPane().add(Ciudad_l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 240, -1, -1));

        Hormigas1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Hormigas1.setText("0");
        getContentPane().add(Hormigas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, -1, -1));

        Ciudades1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Ciudades1.setText("0");
        getContentPane().add(Ciudades1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, -1, -1));

        Ciclos1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Ciclos1.setText("0");
        getContentPane().add(Ciclos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, -1, -1));

        Feromonas1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Feromonas1.setText("0");
        getContentPane().add(Feromonas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, -1, -1));

        Visibilidad1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Visibilidad1.setText("0");
        getContentPane().add(Visibilidad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, -1, -1));

        Evaporacion1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Evaporacion1.setText("0");
        getContentPane().add(Evaporacion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 270, -1, -1));

        Ciudad_p1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Ciudad_p1.setText("0");
        getContentPane().add(Ciudad_p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 210, -1, -1));

        Carga2.setText("Cargar");
        Carga2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Carga2ActionPerformed(evt);
            }
        });
        getContentPane().add(Carga2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 430, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel13.setText("- Número de hormigas:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel14.setText("- Número de ciudades:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel15.setText("- Número de ciclos:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel16.setText("- Grado de feromonas:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 370, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel17.setText("- Grado de visibilidad:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, -1, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel18.setText("- Factor de evaporación: ");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 430, -1, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel19.setText("- Ciudad de partida:");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 370, -1, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel20.setText("- Ciudad de llegada:");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 400, -1, -1));

        Ciudad_l2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Ciudad_l2.setText("0");
        getContentPane().add(Ciudad_l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 400, -1, -1));

        Hormigas2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Hormigas2.setText("0");
        getContentPane().add(Hormigas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, -1, -1));

        Ciudades2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Ciudades2.setText("0");
        getContentPane().add(Ciudades2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, -1, -1));

        Ciclos2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Ciclos2.setText("0");
        getContentPane().add(Ciclos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 430, -1, -1));

        Feromonas2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Feromonas2.setText("0");
        getContentPane().add(Feromonas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 370, -1, -1));

        Visibilidad2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Visibilidad2.setText("0");
        getContentPane().add(Visibilidad2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 400, -1, -1));

        Evaporacion2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Evaporacion2.setText("0");
        getContentPane().add(Evaporacion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 430, -1, -1));

        Ciudad_p2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Ciudad_p2.setText("0");
        getContentPane().add(Ciudad_p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 370, -1, -1));

        Carga3.setText("Cargar");
        Carga3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Carga3ActionPerformed(evt);
            }
        });
        getContentPane().add(Carga3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 590, -1, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel21.setText("- Número de hormigas:");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, -1, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel22.setText("- Número de ciudades:");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, -1, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel23.setText("- Número de ciclos:");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 590, -1, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel24.setText("- Grado de feromonas:");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 530, -1, -1));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel25.setText("- Grado de visibilidad:");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 560, -1, -1));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel26.setText("- Factor de evaporación: ");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 590, -1, -1));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel27.setText("- Ciudad de partida:");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 530, -1, -1));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel28.setText("- Ciudad de llegada:");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 560, -1, -1));

        Ciudad_l3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Ciudad_l3.setText("0");
        getContentPane().add(Ciudad_l3, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 560, -1, -1));

        Hormigas3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Hormigas3.setText("0");
        getContentPane().add(Hormigas3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 530, -1, -1));

        Ciudades3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Ciudades3.setText("0");
        getContentPane().add(Ciudades3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 560, -1, -1));

        Ciclos3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Ciclos3.setText("0");
        getContentPane().add(Ciclos3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 590, -1, -1));

        Feromonas3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Feromonas3.setText("0");
        getContentPane().add(Feromonas3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 530, -1, -1));

        Visibilidad3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Visibilidad3.setText("0");
        getContentPane().add(Visibilidad3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 560, -1, -1));

        Evaporacion3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Evaporacion3.setText("0");
        getContentPane().add(Evaporacion3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 590, -1, -1));

        Ciudad_p3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Ciudad_p3.setText("0");
        getContentPane().add(Ciudad_p3, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 530, -1, -1));

        Salida.setBackground(new java.awt.Color(255, 0, 0));
        Salida.setText("X");
        Salida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalidaActionPerformed(evt);
            }
        });
        getContentPane().add(Salida, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 10, 80, -1));

        Volver.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        Volver.setText("←");
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });
        getContentPane().add(Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 80, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Carga1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Carga1ActionPerformed
        this.setVisible(false);
        Menú ventana = new Menú();
        ventana.setVisible(true);
    }//GEN-LAST:event_Carga1ActionPerformed

    private void Carga2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Carga2ActionPerformed
        this.setVisible(false);
        Menú ventana = new Menú();
        ventana.setVisible(true);
    }//GEN-LAST:event_Carga2ActionPerformed

    private void Carga3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Carga3ActionPerformed
        this.setVisible(false);
        Menú ventana = new Menú();
        ventana.setVisible(true);
    }//GEN-LAST:event_Carga3ActionPerformed

    private void SalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalidaActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SalidaActionPerformed

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cargar_Gr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cargar_Gr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cargar_Gr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cargar_Gr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cargar_Gr().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Carga1;
    private javax.swing.JButton Carga2;
    private javax.swing.JButton Carga3;
    private javax.swing.JButton Carga_0;
    private javax.swing.JTextField Ciclos1;
    private javax.swing.JTextField Ciclos2;
    private javax.swing.JTextField Ciclos3;
    private javax.swing.JTextField Ciudad_l1;
    private javax.swing.JTextField Ciudad_l2;
    private javax.swing.JTextField Ciudad_l3;
    private javax.swing.JTextField Ciudad_p1;
    private javax.swing.JTextField Ciudad_p2;
    private javax.swing.JTextField Ciudad_p3;
    private javax.swing.JTextField Ciudades1;
    private javax.swing.JTextField Ciudades2;
    private javax.swing.JTextField Ciudades3;
    private javax.swing.JTextField Evaporacion1;
    private javax.swing.JTextField Evaporacion2;
    private javax.swing.JTextField Evaporacion3;
    private javax.swing.JTextField Feromonas1;
    private javax.swing.JTextField Feromonas2;
    private javax.swing.JTextField Feromonas3;
    private javax.swing.JTextField Hormigas1;
    private javax.swing.JTextField Hormigas2;
    private javax.swing.JTextField Hormigas3;
    private javax.swing.JButton Salida;
    private javax.swing.JTextField Visibilidad1;
    private javax.swing.JTextField Visibilidad2;
    private javax.swing.JTextField Visibilidad3;
    private javax.swing.JButton Volver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
