/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

/**
 *
 * @author yangel
 */
public class Crear_Ciu extends javax.swing.JFrame {

    /**
     * Creates new form Crear_Ciu
     */
    public Crear_Ciu() {
        initComponents();
        Crear.setVisible(false); 
        
        Ciudad.setVisible(false);
        Ciudad_lb.setVisible(false);
        
        
        Ciudad_ad.setVisible(false);
        Ciudad_ad_Título.setVisible(false);
        Ciudad_ad_lb.setVisible(false);
        
        Distancia.setVisible(false);
        Distancia_lb.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Ciudad_ad_lb = new javax.swing.JLabel();
        Distancia_lb = new javax.swing.JLabel();
        Ciudad_lb = new javax.swing.JLabel();
        Ciudad = new javax.swing.JLabel();
        Ciudad_ad_Título = new javax.swing.JLabel();
        Ciudad_ad = new javax.swing.JLabel();
        Crear = new javax.swing.JButton();
        Distancia = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Ciudad_ad_lb.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Ciudad_ad_lb.setText("Ciudad adyacente:");
        jPanel1.add(Ciudad_ad_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 200, -1, -1));

        Distancia_lb.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Distancia_lb.setText("Distancia:");
        jPanel1.add(Distancia_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, -1, -1));

        Ciudad_lb.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Ciudad_lb.setText("Número de ciudad:");
        jPanel1.add(Ciudad_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, -1, -1));

        Ciudad.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        Ciudad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Ciudad.setText("1");
        jPanel1.add(Ciudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 50, -1));

        Ciudad_ad_Título.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Ciudad_ad_Título.setText("Ciudades Adyacentes");
        jPanel1.add(Ciudad_ad_Título, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, -1, -1));

        Ciudad_ad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Ciudad_ad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Ciudad_ad.setText("0");
        jPanel1.add(Ciudad_ad, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 200, 30, -1));

        Crear.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Crear.setText("Crear");
        Crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearActionPerformed(evt);
            }
        });
        jPanel1.add(Crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 380, 170, -1));

        Distancia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Distancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DistanciaActionPerformed(evt);
            }
        });
        jPanel1.add(Distancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 230, 70, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setText("Crear ciudad");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearActionPerformed
        this.setVisible(false);
        Menú ventana = new Menú();
        ventana.setVisible(true);
        
    }//GEN-LAST:event_CrearActionPerformed

    private void DistanciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DistanciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DistanciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Crear_Ciu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Crear_Ciu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Crear_Ciu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Crear_Ciu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Crear_Ciu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Ciudad;
    private javax.swing.JLabel Ciudad_ad;
    private javax.swing.JLabel Ciudad_ad_Título;
    private javax.swing.JLabel Ciudad_ad_lb;
    private javax.swing.JLabel Ciudad_lb;
    private javax.swing.JButton Crear;
    private javax.swing.JTextField Distancia;
    private javax.swing.JLabel Distancia_lb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
